{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c75a947f",
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mThe kernel failed to start as the Python Environment 'Python 3.12.8' is no longer available. Consider selecting another kernel or refreshing the list of Python Environments."
     ]
    }
   ],
   "source": [
    "from src.data_retrieval import fetch_data\n",
    "from src.analysis import add_moving_average, daily_returns\n",
    "from src.visualization import plot_price\n",
    "\n",
    "df = fetch_data(\"AAPL\", period=\"6mo\")\n",
    "df = add_moving_average(df)\n",
    "df = daily_returns(df)\n",
    "plot_price(df, \"AAPL\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
